### ISSUE TITLE
Enable documentation build on pull requests in readthedocs

### ISSUE THREAD

**Issue by Mariatta** [brettcannon/gidgethub#113]
It would be great if we can enable the new documentation build feature from readthedocs.

Details: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by brettcannon** [comment]
Definitely fine by me! Did you want to email to get us into the beta?

**Comment by Mariatta** [comment]
I've sent the email, they said it's been enabled, but I don't see it in https://github.com/brettcannon/gidgethub/pull/117

I don't have access to gidgethub in readthedocs. If you have time to look into it, it would be great.

**Comment by brettcannon** [comment]
I've done everything I can, so if what I just did  doesn't work then we will have to reach out.

And if you send me your RTD username I will add you as an admin.

**Comment by Mariatta** [comment]
Thankns. my RTD username is `mariatta`

**Comment by brettcannon** [comment]
@Mariatta done!
