### ISSUE TITLE
Changelog header is missing from the documentation

### ISSUE THREAD

**Issue by Mariatta** [brettcannon/gidgethub#118]
It would be great to add that back. I saw it was removed in https://github.com/brettcannon/gidgethub/commit/29452d1c4b87beb3b73769bb4f36c964f1461010

Not sure is this is the required format for `release-often`? Or was it mistakenly removed?

![Screen Shot 2020-04-23 at 10 28 50 AM](https://user-images.githubusercontent.com/5844587/80130538-95c65300-854d-11ea-833d-a4574d5594d4.png)

It would be great if we can keep the Changelog header.

**Comment by brettcannon** [comment]
It was taken out on purpose as release-often just prepends to the changelog file to keep things simple. But apparently Sphinx doesn't normalize section headers across a project, so it's just treating it the same no matter what separate is used. 😠

I'll update release-often.

**Comment by brettcannon** [comment]
Fixed by https://github.com/brettcannon/gidgethub/commit/4e51ad27b5079b8bd69d1eb118391232d5da7984
