### ISSUE TITLE
Test POST using httpbin

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/gidgethub#12]
As https://github.com/brettcannon/gidgethub/pull/11 discovered, testing that POST works as expected is important, so writing a test that uses https://httpbin.org/ to just make sure everything is set up to at least not fail on a POST with a body would be good (GET requests are already covered by the rate limit test).

**Comment by brettcannon** [comment]
@Lukasa unless you have a better idea to test where you don't have to worry about unauthenticated GitHub requests that won't erratically fail thanks to Travis not having any quota?

**Comment by brettcannon** [comment]
And just to help document, the entire reason making sure that `content-length` is done properly is https://developer.github.com/v3/issues/#lock-an-issue.

**Comment by Lukasa** [comment]
I think that the httpbin test is just fine as an approach.

**Comment by brettcannon** [comment]
OK, then I think I will write up a 0-length PUT test and a non-0-length POST test for aiohttp and then let you know here when that's done in case you want to write one for treq.

**Comment by brettcannon** [comment]
I realized that posting is tricky to test due to the attempt to parse all of the GitHub response headers that httpbin won't reflect in the header itself. So instead I created #13 which just does an integration test which would have caught the issue.

**Comment by brettcannon** [comment]
I'm going to close this as I view #13 as covering the necessary issues that I was worried about. If I really care I could always write another subclass that passed requests down to e.g. aiohttp but then injected relevant GitHub headers in the results to make everything pass, but that seems like overkill.
