### ISSUE TITLE
Got weird error when using gidgethub

### ISSUE THREAD

**Issue by randytli** [brettcannon/gidgethub#129]
Hi! I got some weird error when using gidgethub to develop my own GitHub app (a Github bot). My bot works well when I tried to update my comments on a PR/issue. However, when I tried to update commit comment(i.e the "patch" action), it always shows: "gidgethub.BadRequest: Resource not accessible by integration". I am not quite sure if this problem is coming from gidgethub or Github REST API. Would you mind give me some advice? Thank you!

**Comment by Mariatta** [comment]
Usually it means the GitHub App does not have the permission to perform that API call. Is the app installed in  the repo, and was it given sufficient privileges, such as read/write code?

Also the error message "Resource not accessible by integration" comes from GitHub, not from Gidgethub. You may be able to get further help and support from GitHub.

**Comment by randytli** [comment]
> Usually it means the GitHub App does not have the permission to perform that API call. Is the app installed in the repo, and was it given sufficient privileges, such as read/write code?
> 
> Also the error message "Resource not accessible by integration" comes from GitHub, not from Gidgethub. You may be able to get further help and support from GitHub.

Thanks for your response! 

Yes, the app is installed in the repo. Actually the repo admin told me that he gave the app such privileges as it could edit comments in the PR/issue. Thus it's so weird that the app can not edit comments for a specific commit in the same PR(though it could post comments).

**Comment by brettcannon** [comment]
Posting a comment does not require write access like it does for editing comments (i.e. you can post a comment with just `public_repo` permissions, but you need write access to edit something).

I'm going to close this as I don't think this has anything to do with gidgethub, but feel free to keep asking questions, @randytli , and we can see if we can help.

**Comment by randytli** [comment]
> Posting a comment does not require write access like it does for editing comments (i.e. you can post a comment with just `public_repo` permissions, but you need write access to edit something).
> 
> I'm going to close this as I don't think this has anything to do with gidgethub, but feel free to keep asking questions, @randytli , and we can see if we can help.

I would double-check this with the repo admin. Thanks for your help!

**Comment by randytli** [comment]
It turns out this problem is because the app does not have write access to the `content` permission. Thanks for your patience and help again!
