### ISSUE TITLE
[mypy] Incorrect type for argument `data` to `httpx.AsyncClient.request`

### ISSUE THREAD

**Issue by dhruvmanila** [brettcannon/gidgethub#133]
Incorrect annotation for argument `data` to `httpx.AsyncClient.request` as referenced in https://github.com/brettcannon/gidgethub/issues/74#issuecomment-723391219

Location in the module: `gidgethub/httpx.py::GitHubAPI::_request(body: bytes = b"")`

Reference:
`httpx` client module: https://github.com/encode/httpx/blob/master/httpx/_client.py#L1334
Type source: https://github.com/encode/httpx/blob/master/httpx/_types.py#L73

```console
gidgethub/httpx.py:19: error: Argument "data" to "request" of "AsyncClient" has incompatible type "bytes"; expected "Dict[Any, Any]"
```

**Comment by brettcannon** [comment]
https://www.python-httpx.org/api/ suggests the argument should be `content`, not `data` for httpx.
