### ISSUE TITLE
Release v 4.2.0

### ISSUE THREAD

**Issue by Mariatta** [brettcannon/gidgethub#136]
The last release to PyPI was v 4.1.1 in June.
The documentation already mentions v 4.2.0 in the changelog https://gidgethub.readthedocs.io/en/latest/changelog.html#id1

Perhaps it's time to cut a release for v 4.2.0. We can also wait after https://github.com/brettcannon/gidgethub/pull/134 gets merged.

I'm opening this issue as a reminder to do it. Do you have a new workflow in mind to handle automated releases? If not, I can do the release the old-fashioned way.

**Comment by brettcannon** [comment]
@Mariatta nope, no new workflow.

**Comment by Mariatta** [comment]
I've just released v4.2.0
On GitHub: https://github.com/brettcannon/gidgethub/releases/tag/v4.2.0
On PyPI: https://pypi.org/project/gidgethub/4.2.0/
