### ISSUE TITLE
Turn on GitHub Discussions?

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/gidgethub#138]
And if so, what categories?

* Q&A (or "Help" or "Support")
* Ideas
* Projects using Gidgethub
* Everything Else

/cc @Mariatta

**Comment by Mariatta** [comment]
Yeah let's do it! 
Can categories be changed/created easily?

**Comment by brettcannon** [comment]
I have absolutely no idea about the difficulty of adding or changing categories. I would assume adding is easy, but probably changing existing ones would have weird consequences of the meaning shifted but discussions stayed there. So we should probably think of what categories we know we want and start small and bring on others as we learn what people may want.

**Comment by Mariatta** [comment]
I think the above categories sound good.

Looking at the [documentation](https://docs.github.com/en/free-pro-team@latest/discussions/managing-discussions-for-your-community/managing-discussions-in-your-repository), it seems like editing/deleting Categories is straightforward, similar to how we would edit/delete Labels. When [deleting a Category](https://docs.github.com/en/free-pro-team@latest/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository#deleting-a-category), we will have the option to move all open discussion items in that Category to another Category. 
Looking at a discussion item in the python/core-sprint repo, it seems like we could easily re-categorize a discussion to another category, just like editing a label in a PR. 

![Screen Shot 2020-12-10 at 2 48 32 PM](https://user-images.githubusercontent.com/5844587/101839413-2fe80500-3af7-11eb-886a-2eba186a8b82.png)

**Comment by brettcannon** [comment]
The default categories make sense, so I went ahead and went with them. We can tweak as we see if there's any uptake.
