### ISSUE TITLE
Provide a caching GitHubAPI mixin

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/gidgethub#20]
Using [`ETag` and `Last-Modified`](https://developer.github.com/v3/#conditional-requests), a mixin which overrides `abc.GitHubAPI._request()` could pass in the appropriate headers and catch a `304` status code to return a cached result. This should only be used on `GET` with no `body`.

**Comment by brettcannon** [comment]
To manage the cache, it could either be total number of bytes or total number of entries. Using an [`OrderedDict`](https://docs.python.org/3/library/collections.html#collections.OrderedDict) might be the easiest way to balance ejecting older entries by [moving accessed keys to the front](https://docs.python.org/3/library/collections.html#collections.OrderedDict.move_to_end). That way fast access is still the priority while keeping some priority order on values exists (and since this is I/O, that reordering of keys shouldn't be expensive in the grand scheme of things).

**Comment by dstufft** [comment]
You might consider depending on cachetools for this.

**Comment by brettcannon** [comment]
https://pypi.org/project/cachetools/

**Comment by brettcannon** [comment]
Some open questions:
1. Least recently used or least frequently used? (Gut says LRU due to data changes being more of a thing than frequency of the call.)
2. Since a page of PRs is 500K but a single PR is 24K, should there be a cap on the size of what gets cached knowing that e.g. a page of PRs will more than likely be stale sooner than a single PR? (Seems like a per-server thing, e.g. a 10 MB cache could get blown out by a daily cron job going through all open PRs, but at 200 MB you just don't care.)
3. Only cache JSON data/urlencoded data, or cache everything regardless of content type? (Leaning towards not caring.)
4. What should the default cache size be (if there even should be a default cache)? (Leaning towards no default since it's so server-specific.)
5. Accept a `cache: MutableMapping` argument to `GitHubAPI` or simplify things for people and just have them specify `cache_size: int` and otherwise bake in the cache strategy? One perk to the `cache` idea is a default cache can be provided which would then span `GitHubAPI` instances which would increase the caching impact. (Leaning towards a `cache: Optional[MutableMapping]` for flexibility.)

**Comment by dstufft** [comment]
(1) LRU I think for the reasons you said.
(2) Configurable maybe?
(3) I'd cache everything, ideally you can layer this on at the HTTP level IMO, doing something like the cachecontrol library does for requests. Ideally even caching Etag and Last-Modified requests to do conditional GETs (which will revalidate stale data, and don't count against API limits IIRC).
(4) I'd say no default.
(5) A Cache implementation seems like a good idea rather than a cache_size thing.

**Comment by brettcannon** [comment]
@dstufft about (3), I would expect to cache every GET request with no body in `GitHubAPI._make_request()` and send the appropriate `If-None-Match` and `If-Modified-Since` headers down through `GitHubAPI._request()` and catch the `304` response (as well as cache any results).
