### ISSUE TITLE
Provide a way to fetch the functions for a given event on a router

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/gidgethub#74]
E.g. `gidgethub.routing.Router.fetch(event) -> typing.Set` to get the set of functions that the event would be called on. This is to facilitate testing by making sure the expected functions have been registered with the router.

**Comment by dhruvmanila** [comment]
If this is still relevant, I think it's pretty easy to implement. You're already doing this in `routing.Router.dispatch()` where you collect all the callbacks which matches the given `event` and then make the calls to the function.

We can separate out the collection part in `routing.Router.fetch` and then use it in `routing.Router.dispatch` before making the calls.

**Comment by brettcannon** [comment]
I can be relevant to someone, but my thinking on this has shifted. I have started to call the routers themselves to dispatch to the callers in my tests, which implicitly means I test that things are wired up appropriately. So while I'm not opposed to exposing this, I don't think I'm personally going to worry about implementing it.

**Comment by dhruvmanila** [comment]
Alright, I can work on this one. I already implemented the changes and everything works as before. If you want I can open a PR for it. Although the coverage hasn't changed, I will create an extra test for `routing.Router.fetch`.

**Comment by brettcannon** [comment]
There's a PR check for 100% branch coverage, so hopefully the coverage hasn't changed 😉

**Comment by dhruvmanila** [comment]
It is going to be 100% :) 

Also, there seems to be a problem with the type hint for the `body` attribute of `httpx.AsyncClient`. Your type hint is `bytes` while the module expects a `dict`.

`httpx` client module: https://github.com/encode/httpx/blob/master/httpx/_client.py#L1334
Type source: https://github.com/encode/httpx/blob/master/httpx/_types.py#L73

**Comment by brettcannon** [comment]
The typing may have changed since that support was written several httpx versions ago. Feel free to fix it in any PR you submit.
