### ISSUE TITLE
Changelog in the docs, instead of / in addition to the readme

### ISSUE THREAD

**Issue by Mariatta** [brettcannon/gidgethub#75]
At the moment, changelog for gidgethub lives in the readme of the project. (https://github.com/brettcannon/gidgethub/blob/master/README.rst)

I think it would be great if the changelog is also in the online documentation (https://gidgethub.readthedocs.io/en/latest/), keeping all the documentation in one place, and easier to discover, instead of needing to go to GitHub and read the readme file.

**Comment by brettcannon** [comment]
I'm fine with moving it, but I wouldn't want to duplicate it in both places.

**Comment by Mariatta** [comment]
😥 Sorry!!! I accidentally pushed to master! 😱

**Comment by Mariatta** [comment]
Working to revert it now.

**Comment by brettcannon** [comment]
:) It's not a big deal since we don't do CD (and even if we did I'm not worried about wonky docs for a little while).
