### ISSUE TITLE
Unhardcode base API URL

### ISSUE THREAD

**Issue by webknjaz** [brettcannon/gidgethub#80]
Currently, enterprise users can patch this like
```python
import gidgethub.sansio
gidgethub.sansio.DOMAIN =  'https://your.enterprise-github.com/v3/'
```

But there should probably be a better way...

cc @rs2

**Comment by brettcannon** [comment]
Doesn't really have to be. async is thread-safe by design so it could actually just become documented. Otherwise I guess an argument to the constructor of `GitHubAPI` to specify the base part of the URL would also be possible.

**Comment by webknjaz** [comment]
Yeah, I think an argument in the initializer sounds good. I don't think that promoting monkey-patching is a good idea + I can imagine an app which would need to talk to several GitHubs. Like migration/sync app or so.

**Comment by webknjaz** [comment]
Note: for some reason, I originally misunderstood this comment https://github.com/brettcannon/gidgethub/blob/94eafc2/gidgethub/sansio.py#L340 and thought that `DOMAIN` would take precedence. So documenting how it really works here:

<details>
<summary>
  </code>$ <kbd>ipython</kbd></code>
</summary>

```python
Python 3.7.1 (default, Jan 28 2019, 08:25:13) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import urllib.parse               

In [2]: DOMAIN = "https://api.github.com" 

In [3]: urllib.parse.urljoin(DOMAIN, 'https://new-server.org/vX/sfa')       
Out[3]: 'https://new-server.org/vX/sfa'
```
</details>

**Comment by brettcannon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow specifying the URL for gidgethub](https://trello.com/c/TPCQ7NvM/285-allow-specifying-the-url-for-gidgethub)

**Comment by Mariatta** [comment]
I created the PR for adding **base_url** parameter to the constructor https://github.com/brettcannon/gidgethub/pull/106
