### ISSUE TITLE
Rename httpx.AsyncClient --> httpx.Client

### ISSUE THREAD

**Issue by dhirschfeld** [brettcannon/gidgethub#90]
To follow upstream:
https://github.com/encode/httpx/pull/544/commits/7898bff8f6fa26ff26f4484a139f027181336a26

**Comment by brettcannon** [comment]
If someone does the work for this it will require a major version bump as the name change would be a breaking change.

**Comment by dhirschfeld** [comment]
You could avoid that by checking versions, or the quick-and-dirty version:
```python
try:
    from httpx import AsyncClient as Client
except ImportError:
    from httpx import Client
```

**Comment by brettcannon** [comment]
@dhirschfeld I thought you wanted to rename `gidgethub.httpx.AsyncClient` and not simply update the package that gets used internally. If you're just after the latter then that's easy to fix. But since support is so new it wouldn't be a huge deal to do a version bump just to cover this misnaming.

**Comment by dhirschfeld** [comment]
I don't think there is a `gidgethub.httpx.AsyncClient`?
https://github.com/brettcannon/gidgethub/blob/master/gidgethub/httpx.py

i.e. `gidgethub.httpx` only defines a `GitHubAPI` class (but it does have a reference to the httpx module which used to have an `AsyncClient` which has since been renamed to `Client`)

In `gidgethub.httpx` the `httpx.AsyncClient` is used only for typing the `client` argument:
https://github.com/brettcannon/gidgethub/blob/94eafc268f70a363a3d271d5941e40f9c807938c/gidgethub/httpx.py#L9-L13

Otherwise, usage of `httpx.AsyncClient` is only in a test and docs:
https://github.com/brettcannon/gidgethub/search?q=AsyncClient&unscoped_q=AsyncClient

where `httpx.AsyncClient` always refers to the encode `httpx` package.

**Comment by brettcannon** [comment]
@dhirschfeld gah, you're right. This is what I get for trying to stay on top of things while I'm swamped at work; reading the code sample at https://gidgethub.readthedocs.io/en/latest/httpx.html too quickly and then my brain just noticing the word `AsyncClient` and not picking up that it's on the context manager from `httpx`.
